version: 2

models:
  - name: rappers
    description: "Contains artists' Spotify data (popularity, followers, associated genres)"
    columns:
      - name: artist_id
        description: "Spotify's artist_id identifier"
        tests:
          - unique
          - not_null
      - name: artist_name
        description: "The artist's name"
        tests:
          - not_null
      - name: popularity
        description: "Artist's popularity according to Spotify - ranges from 0 to 100"
        tests:
          - not_null
      - name: followers
        description: "Artist's follower count"
        tests:
          - not_null
      - name: genres
        description: "String containing up to 3 genres associated with the artist"
      - name: is_valid_genre
        description: "Flags if the artist's genres contain any of the (arbitrary) main rap genres"
        tests:
          - not_null
      - name: is_excluded_genre
        description: "Flags if the artist's genres contain any of the (arbitrary) non-rap genres and don't contain \"hip hop\""
        tests:
          - not_null
      - name: image_url
        description: "URL for the artist's profile picture on Spotify"
      - name: load_date
        description: "Timestamp for when the record was initially loaded to Postgres from Spotify's API"
        tests:
          - not_null

  - name: top_tracks
    description: "Contains up to top 5 tracks associated with given artist within Spotify's US market"
    columns:
      - name: artist_id
        description: "Spotify's artist_id identifier"
        tests:
          - not_null
          - relationships:
              to: ref('rappers')
              field: artist_id
      - name: track_rank
        description: "Rank for the track, according to Spotify's US market. A record with track_rank = 2 means it is the artist's second top track."
        tests:
          - not_null
      - name: track_name
        description: "The track (song) name"
        tests:
          - not_null
      - name: track_id
        description: "Spotify's track_id identifier"
        tests:
          - not_null
      - name: track_url
        description: "URL to play the track on Spotify"
        tests:
          - not_null
      - name: preview_url
        description: "URL for a short snippet/preview of the track - often not available"
      - name: load_date
        description: "Timestamp for when the record was initially loaded to Postgres from Spotify's API"
        tests:
          - not_null

  - name: rappers_filtered
    description: "Contains artists' Spotify data filtered by popularity, genres and followers"
    columns:
      - name: artist_id
        description: "Spotify's artist_id identifier"
        tests:
          - unique
          - not_null
      - name: artist_name
        description: "The artist's name"
        tests:
          - not_null
      - name: popularity
        description: "Artist's popularity according to Spotify - ranges from 0 to 100"
        tests:
          - not_null
      - name: followers
        description: "Artist's follower count"
        tests:
          - not_null
      - name: genres
        description: "String containing up to 3 genres associated with the artist"
      - name: image_url
        description: "URL for the artist's profile picture on Spotify"
      - name: load_date
        description: "Timestamp for when the record was initially loaded to Postgres from Spotify's API"
        tests:
          - not_null