name: 'battle_rap'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  battle_rap:
    staging:
      schema: staging
      +materialized: view
    battle_rap:
      schema: battle_rap
      +materialized: table
