
name: 'dbt_models_wow'
version: '1.0.0'
config-version: 2

profile: 'dbt_models'

model-paths: ["models"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_models:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: table
